---
title: 'Time Series: A First Course with Bootstrap Starter'
output:
  html_document:
    df_print: paged
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/neide/OneDrive/Documents/GitHub/BEwebinar/Data')
```

# Lesson 6-6: AR and MA Identification 

- How do we determine a model to be fitted? AR, MA, ARMA, or something else?
- How do we determine the order of the model?

## Paradigm 6.6.1. Characterizing AR and MA Processes

- The autocorrelation function (ACF) and partial autocorrelation function (PACF) have distinctive behavior for AR and MA processes.

### ACF

- For an MA($q$) process, the ACF truncates at lag $q$, i.e., $\gamma (h) = 0$ if $|h| >q$. However, it is possible for $\gamma (h) = 0$ for $0 < h <q$ as well.
- For an AR($p$) process, or for an ARMA($p$,$q$) process (with $p > 0$), the ACF decays at geometric rate. The correlations can oscillate, but they are bounded by some $C r^{|h|}$ for $0 < r < 1$ and $C >0$.

### PACF

- For an AR($p$) process, the PACF truncates at lag $p$, i.e., $\kappa (h) = 0$ if $|h|>p$.
- for an MA($q$) process, or for an ARMA($p$,$q$) process (with $q > 0$), the PACF decays at geometric rate.

### Finding Truncation

We can plot estimates of the ACF and PACF, and see if there is a lag cut-off where one or the other seems to negligible.  


HERE: add examples...
