---
title: 'Time Series: A First Course with Bootstrap Starter'
output:
  html_document:
    df_print: paged
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/neide/OneDrive/Documents/GitHub/BEwebinar/Data')
```

# Lesson 5-6: Autocovariance Generating Function

- We want a way to summarize the autocovariances for an ARMA process.

## Definition 5.6.1.

The *autocovariance generating function* (AGF) of a stationary time series with autocovariance function $\gamma (k)$ is
\[
  G(z) = \sum_{k = - \infty}^{\infty} \gamma (k) z^k
\]
 (if it converges in some annulus $1/r < |z| < r$ for $r > 1$).
 
## Example 5.6.3. Constant AGF

- Suppose $X_t \sim \mbox{WN}(0, \sigma^2)$. Then $\gamma (0) = \sigma^2$, and $\gamma (k) = 0$ if $k \neq 0$. Hence
\[
  G(z) = \gamma (0) = \sigma^2.
\]
- The AGF for white noise is a constant function.
 
## Definition 5.6.5.

- Suppose that $Y_t = \psi (B) X_t$ for some linear filter $\psi (B)$. For complex $z$,
the *transfer function* of the filter is $\psi (z)$. Its coefficients $\psi_j$ are
the *impulse response coefficients*.
 
## Theorem 5.6.6.

Suppose we filter stationary $\{ X_t \}$ with some $\psi (B)$, yielding $Y_t = \psi (B) X_t$. Then the AGFs of input and output are related by
\[
   G_y (z) = \psi (z) \psi (z^{-1}) G_x (z).
\]

## Remark 5.6.8. ARMA Transfer Function

- Because a causal ARMA can be written in MA representation as $X_t = \psi (B) Z_t$, we have
\[
  G_x (z) = \psi (z) \psi (z^{-1}) \sigma^2,
\]
 by Example 5.6.3.  
- Using $\psi (z) = \theta (z)/ \phi (z)$, we obtain
\[
  G_x (z) =  \frac{ \theta (z) \theta (z^{-1}) }{ \phi (z) \phi (z^{-1}) } \sigma^2.
\]

## Example 5.6.9. MA(1) AGF

- We can use the AGF to compute autocovariances from MA parameters.
- Suppose $\{ X_t \}$ is an MA(1) process with polynomial $\theta(z) = 1 + \theta_1 z$. Then
\[
 G_x (z) = \theta (z) \theta (z^{-1}) \sigma^2
  = (1 + \theta_1 z) (1 + \theta_1 z^{-1}) \sigma^2 
   = \left( 1 + \theta_1^2 + \theta_1 z + \theta_1 z^{-1} \right) \sigma^2.
\]
- Because the coefficient of $z^0 = 1$ is $\gamma (0)$, we have
\[
 \gamma (0 ) = (1 + \theta_1^2) \sigma^2.
\]
- Also, the coefficient of both $z$ and $z^{-1}$ is $\gamma (1)$. Therefore
\[
 \gamma (1) = \theta_1 \sigma^2.
\]

## Example 5.6.10. AR(1) AGF

- We can also compute the AGF for an AR(1).
- Suppose $\{ X_t \}$ is an AR(1) with causal polynomial $\phi (z) = 1 - \phi_1 z$. Then
\[
 G_x (z) = \frac{1}{ \phi (z) \phi (z^{-1})} \sigma^2 
  = \frac{1}{ (1 - \phi_1 z) (1 - \phi_1 z^{-1})} \sigma^2.
\]
- By geometric series, 
\[
  {(1 -  \phi_1 z)}^{-1} = \sum_{j \geq 0} \phi_1^j z^j.
\]
 (Causality guarantees that $|\phi_1| < 1$!)
- Therefore
\begin{align*}
 G_x (z) & = \left( \sum_{j \geq 0} \phi_1^j z^j \right) 
 \left( \sum_{j \geq 0} \phi_1^j z^{-j} \right) \sigma^2 \\
 & = \sum_{j,k \geq 0} \phi_1^{j+k} z^{j-k} \sigma^2 \\
 & = \sum_{h = -\infty}^{\infty} \sum_{k \geq 0} \phi_1^{|h| + 2k} z^h \sigma^2 \\
 & = \sum_{h = -\infty}^{\infty} \frac{ \phi_1^{|h|}}{1 - \phi_1^2} z^h \sigma^2.
\end{align*}
- Now we read off the coefficient of $z^h$ (or $z^{-h}$) is $\gamma (h)$:
\[
 \gamma (h) = \frac{ \phi_1^{|h|}}{1 - \phi_1^2} \sigma^2.
\]

